fullData<-read.csv("household_power_consumption.txt",na.strings ="?",sep=";")
fullData$DateTime<-paste(fullData$Date,fullData$Time)
fullData$DateTime<-strptime(fullData$DateTime,format="%d/%m/%Y %H:%M:%S")
fullData$Date<-as.Date(fullData$Date,"%d/%m/%Y")
plotData<-subset(fullData,(Date == "2007-02-01" | Date == "2007-02-02"))
png(file = "plot3.png", width = 480, height = 480, units = "px",bg = "transparent")
plot(plotData$DateTime,plotData$Sub_metering_1,type='l',col='black',ylab="Energy sub metering",xlab="")
lines(plotData$DateTime,plotData$Sub_metering_2,type='l',col='blue',ylab="Energy sub metering",xlab='')
lines(plotData$DateTime,plotData$Sub_metering_3,type='l',col='blue',ylab="Energy sub metering",xlab='')
dev.off()