fullData<-read.csv("household_power_consumption.txt",na.strings ="?",sep=";")
fullData$DateTime<-paste(fullData$Date,fullData$Time)
fullData$DateTime<-strptime(fullData$DateTime,format="%d/%m/%Y %H:%M:%S")
fullData$Date<-as.Date(fullData$Date,"%d/%m/%Y")
plotData<-subset(fullData,(Date == "2007-02-01" | Date == "2007-02-02"))
png(file = "plot4.png", width = 480, height = 480, units = "px",bg = "transparent")
par(mfrow=c(2,2))
plot(plotData$DateTime,plotData$Global_active_power,type='l',ylab="Global Active Power (kilowatts)",xlab="")
plot(plotData$DateTime,plotData$Voltage,type='l',ylab="Voltage",xlab="datetime")
plot(plotData$DateTime,plotData$Sub_metering_1,type='l',col='black',ylab="Energy sub metering",xlab="")
lines(plotData$DateTime,plotData$Sub_metering_2,type='l',col='blue',ylab="Energy sub metering",xlab='')
lines(plotData$DateTime,plotData$Sub_metering_3,type='l',col='blue',ylab="Energy sub metering",xlab='')
plot(plotData$DateTime,plotData$Global_reactive_power,type='l',ylab="Global Reactive Power (kilowatts)",xlab="")
dev.off()